name: Update README

on:
  push:
    branches:
      - main
      - workflow-experimental

jobs:
  build:
    if: 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: python -m pip install --upgrade pillow

      - name: Update README
        run: |
          python .github/scripts/update_readme.py
          git add README.md
          git config --local user.email "lmao@github.com"
          git config --local user.name "Lmao"
          git commit -m "Update README.md"
          git push
